In [2]:
import pandas as pd

%load_ext autoreload
%autoreload 2

In [3]:
fname = 'test.df'

#Read test hdf5 
pfp_inds = pd.read_hdf(fname,key='pfp_inds')
pfp = pd.read_hdf(fname,key='pfp')

hdr_inds = pd.read_hdf(fname,key='hdr_inds')
hdr = pd.read_hdf(fname,key='hdr')

mcnu_inds = pd.read_hdf(fname,key='mcnu_inds')
mcnu = pd.read_hdf(fname,key='mcnu')

mcprim_inds = pd.read_hdf(fname,key='mcprim_inds')
mcprim = pd.read_hdf(fname,key='mcprim')

In [4]:
pfp_inds

               parent_is_primary slcID trackScore parent id  t0         trk  \
                                                                   producer



run subrun evt
1   0      1                   1     2  -5.000000     -1  2 NaN  4294967295
           1                   1     2   0.530454      2  1 NaN           0
           1                   1     2   0.430532      2  0 NaN           0
           2                   1     1  -5.000000     -1  1 NaN  4294967295
           2                   1     1   0.479985      1  0 NaN           0

                                                    ...         shw  \
                     start                          ...       truth
                         x           y           z  ...           p
                                                    ...         end
                                                    ...           y
run subrun evt                                      ...
1   0      1           NaN         NaN         NaN  ...         NaN
           1     99.229301 -181.469772  277.732086  ... -180.218277
           1     99.487328 -181.321655  293.229980  ... -180.218277
           2           NaN         NaN         NaN  ...         NaN
           2   -174.313965 -114.864754  267.193878  ... -117.086205

                                                                     \


                                genp                         length
                         z         x         y         z
run subrun evt
1   0      1           NaN       NaN       NaN       NaN        NaN
           1    315.257080  0.015783  0.006067  0.441680  39.099953
           1    315.257080  0.015783  0.006067  0.441680  39.099953
           2           NaN       NaN       NaN       NaN        NaN
           2    288.513947 -0.005192 -0.010612  0.130147  23.128178




                      G4ID cont_tpc      genE interaction_id

run subrun evt
1   0      1   -2147483648        0       NaN    -2147483648
           1             2        1  0.442003              0
           1             2        1  0.442003              0
           2   -2147483648        0       NaN    -2147483648
           2             2        1  0.130684              0

[5 rows x 106 columns]

In [5]:
pfp

                                             parent_is_primary slcID  \




entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                                       1     2
                     1                                       1     2
                     2                                       1     2
1     0              0                                       1     1
                     1                                       1     1

                                             trackScore parent id  t0  \




entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                        -5.000000     -1  2 NaN
                     1                         0.530454      2  1 NaN
                     2                         0.430532      2  0 NaN
1     0              0                        -5.000000     -1  1 NaN
                     1                         0.479985      1  0 NaN

                                                     trk              \
                                                producer       start
                                                                   x


entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                        4294967295         NaN
                     1                                 0   99.229301
                     2                                 0   99.487328
1     0              0                        4294967295         NaN
                     1                                 0 -174.313965

                                                                      ...  \
                                                                      ...
                                                       y           z  ...
                                                                      ...
                                                                      ...
entry rec.slc..index rec.slc.reco.pfp..index                          ...
0     0              0                               NaN         NaN  ...
                     1                       -181.469772  277.732086  ...
                     2                       -181.321655  293.229980  ...
1     0              0                               NaN         NaN  ...
                     1                       -114.864754  267.193878  ...

                                                     shw              \
                                                   truth
                                                       p
                                                     end
                                                       y           z
entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                               NaN         NaN
                     1                       -180.218277  315.257080
                     2                       -180.218277  315.257080
1     0              0                               NaN         NaN
                     1                       -117.086205  288.513947

                                                                            \


                                                  genp
                                                     x         y         z
entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                             NaN       NaN       NaN
                     1                        0.015783  0.006067  0.441680
                     2                        0.015783  0.006067  0.441680
1     0              0                             NaN       NaN       NaN
                     1                       -0.005192 -0.010612  0.130147

                                                                              \


                                                 length        G4ID cont_tpc

entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                              NaN -2147483648        0
                     1                        39.099953           2        1
                     2                        39.099953           2        1
1     0              0                              NaN -2147483648        0
                     1                        23.128178           2        1




                                                  genE interaction_id

entry rec.slc..index rec.slc.reco.pfp..index
0     0              0                             NaN    -2147483648
                     1                        0.442003              0
                     2                        0.442003              0
1     0              0                             NaN    -2147483648
                     1                        0.130684              0

[5 rows x 106 columns]

In [6]:
mcnu_inds

                       E    position                         pdg iscc  \
                                   x           y           z
run subrun evt
1   0      1    0.797869   99.285927 -181.421265  277.786041  14    0
           2    0.578487 -174.385406 -114.858246  267.144379  14    0

               genie_mode

run subrun evt
1   0      1            5
           2            5

In [7]:
mcnu

                               E    position                         pdg iscc  \
                                           x           y           z
entry rec.mc.nu..index
0     0                 0.797869   99.285927 -181.421265  277.786041  14    0
1     0                 0.578487 -174.385406 -114.858246  267.144379  14    0

                       genie_mode

entry rec.mc.nu..index
0     0                         5
1     0                         5

In [8]:
hdr_inds

                         pot  first_in_subrun  ngenevt  proc  cluster
run subrun evt
1   0      1    5.751995e+18                1        2    -1       -1
           2    0.000000e+00                0        2    -1       -1

In [9]:
hdr

                pot  first_in_subrun  run  subrun  ngenevt  evt  proc  cluster
entry
0      5.751995e+18                1    1       0        2    1    -1       -1
1      0.000000e+00                0    1       0        2    2    -1       -1

In [10]:
mcprim_inds

               start_process end_process pdg    startE       start  \
                                                                 x
run subrun evt
1   0      1               0          60  14  0.356376   99.285927
           1               0          52  11  0.442003   99.285927
           2               0          60  14  0.448314 -174.385406
           2               0          52  11  0.130684 -174.385406

                                               end                          \
                         y           z           x           y           z
run subrun evt
1   0      1   -181.421265  277.786041  103.302307 -194.370804  509.399994
           1   -181.421265  277.786041   96.731537 -180.218277  315.257080
           2   -114.858246  267.144379 -174.152328 -112.323021  509.399994
           2   -114.858246  267.144379 -172.663788 -117.086205  288.513947

                    genp                          length G4ID cont_tpc  \
                       x         y         z
run subrun evt
1   0      1    0.006169 -0.019891  0.355767  232.010437    3        0
           1    0.015783  0.006067  0.441680   39.099953    2        1
           2    0.000431  0.004691  0.448289  242.268997    3        0
           2   -0.005192 -0.010612  0.130147   23.128178    2        1

                    genE interaction_id

run subrun evt
1   0      1    0.356376              0
           1    0.442003              0
           2    0.448314              0
           2    0.130684              0

In [11]:
mcprim

                                             start_process end_process pdg  \

entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                                 0          60  14
                       1                                 0          52  11
1     0                0                                 0          60  14
                       1                                 0          52  11

                                                startE       start  \
                                                                 x
entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                      0.356376   99.285927
                       1                      0.442003   99.285927
1     0                0                      0.448314 -174.385406
                       1                      0.130684 -174.385406

                                                                      \
                                                       y           z
entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                     -181.421265  277.786041
                       1                     -181.421265  277.786041
1     0                0                     -114.858246  267.144379
                       1                     -114.858246  267.144379

                                                     end              \
                                                       x           y
entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                      103.302307 -194.370804
                       1                       96.731537 -180.218277
1     0                0                     -174.152328 -112.323021
                       1                     -172.663788 -117.086205

                                                              genp            \
                                                       z         x         y
entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                      509.399994  0.006169 -0.019891
                       1                      315.257080  0.015783  0.006067
1     0                0                      509.399994  0.000431  0.004691
                       1                      288.513947 -0.005192 -0.010612

                                                            length G4ID  \
                                                     z
entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                      0.355767  232.010437    3
                       1                      0.441680   39.099953    2
1     0                0                      0.448289  242.268997    3
                       1                      0.130147   23.128178    2

                                             cont_tpc      genE interaction_id

entry rec.mc.nu..index rec.mc.nu.prim..index
0     0                0                            0  0.356376              0
                       1                            1  0.442003              0
1     0                0                            0  0.448314              0
                       1                            1  0.130684              0